# Generated by Django 4.2.6 on 2023-11-12 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="original_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reposts",
                to="questions.question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="repost",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
