# Generated by Django 4.2.6 on 2023-11-12 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_question_original_question_question_repost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="repost",
            new_name="repost_count",
        ),
    ]
