# Generated by Django 4.2.6 on 2023-11-14 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0004_question_reposed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="reposed",
            new_name="reposted",
        ),
    ]
