# Generated by Django 4.2.6 on 2023-10-18 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="likes",
            field=models.ManyToManyField(blank=True, related_name="blog_likes", to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.CharField(max_length=255)),
                ("comment_pub_date", models.DateTimeField(auto_now_add=True)),
                ("Blog", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="blog.blog")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="blog",
            name="comments",
            field=models.ManyToManyField(
                related_name="blog_comments", through="blog.Comment", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
