# Generated by Django 4.2.6 on 2023-10-18 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_likes_comment_blog_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="Blog",
            new_name="blog",
        ),
    ]
