# Generated by Django 4.2.6 on 2023-10-19 19:03

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("blog", "0003_rename_blog_comment_blog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="tags",
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
