# Generated by Django 4.2.6 on 2023-11-05 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_bookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="comments",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="blog.comment"
            ),
        ),
    ]
