# Generated by Django 4.2.6 on 2023-11-12 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_remove_bookmark_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="original_post",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="blog.blog"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="repost",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
