# Generated by Django 4.2.6 on 2023-10-28 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSocialMeiaLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[("facebook", "facebook"), ("instagram", "instagram"), ("X", "X")],
                        max_length=28,
                        null=True,
                    ),
                ),
                ("link", models.URLField(max_length=255)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
