# Generated by Django 4.2.6 on 2023-10-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_usersocialmeialink"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
