# Generated by Django 4.2.6 on 2023-10-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_link_user_social_media_chocies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
