# Generated by Django 4.2.6 on 2023-10-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(blank=True, default="None", max_length=128, null=True),
        ),
    ]
