# Generated by Django 4.2.6 on 2023-10-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about_me",
            field=models.TextField(blank=True, null=True),
        ),
    ]
